<?php

namespace Database\Seeders;

use App\Models\Division;
use App\Models\District;
use App\Models\Upazila;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $divisions = [
            [
                'slug' => 'dhaka', 'name_bn' => 'ঢাকা', 'name_en' => 'Dhaka',
                'districts' => [
                    ['slug' => 'dhaka', 'name_bn' => 'ঢাকা', 'name_en' => 'Dhaka', 'upazilas' => [
                        ['slug' => 'dhanmondi', 'name_bn' => 'ধানমণ্ডি', 'name_en' => 'Dhanmondi'],
                        ['slug' => 'gulshan', 'name_bn' => 'গুলশান', 'name_en' => 'Gulshan'],
                        ['slug' => 'mirpur', 'name_bn' => 'মিরপুর', 'name_en' => 'Mirpur'],
                        ['slug' => 'motijheel', 'name_bn' => 'মতিঝিল', 'name_en' => 'Motijheel'],
                        ['slug' => 'uttara', 'name_bn' => 'উত্তরা', 'name_en' => 'Uttara'],
                        ['slug' => 'mohammadpur', 'name_bn' => 'মোহাম্মদপুর', 'name_en' => 'Mohammadpur'],
                        ['slug' => 'tejgaon', 'name_bn' => 'তেজগাঁও', 'name_en' => 'Tejgaon'],
                        ['slug' => 'lalbagh', 'name_bn' => 'লালবাগ', 'name_en' => 'Lalbagh'],
                        ['slug' => 'demra', 'name_bn' => 'ডেমরা', 'name_en' => 'Demra'],
                        ['slug' => 'sabujbagh', 'name_bn' => 'সবুজবাগ', 'name_en' => 'Sabujbagh'],
                    ]],
                    ['slug' => 'gazipur', 'name_bn' => 'গাজীপুর', 'name_en' => 'Gazipur', 'upazilas' => [
                        ['slug' => 'gazipur-sadar', 'name_bn' => 'গাজীপুর সদর', 'name_en' => 'Gazipur Sadar'],
                        ['slug' => 'kaliakair', 'name_bn' => 'কালিয়াকৈর', 'name_en' => 'Kaliakair'],
                        ['slug' => 'kapasia', 'name_bn' => 'কাপাসিয়া', 'name_en' => 'Kapasia'],
                        ['slug' => 'sreepur', 'name_bn' => 'শ্রীপুর', 'name_en' => 'Sreepur'],
                        ['slug' => 'kaliganj-gazipur', 'name_bn' => 'কালীগঞ্জ', 'name_en' => 'Kaliganj'],
                    ]],
                    ['slug' => 'narayanganj', 'name_bn' => 'নারায়ণগঞ্জ', 'name_en' => 'Narayanganj', 'upazilas' => [
                        ['slug' => 'narayanganj-sadar', 'name_bn' => 'নারায়ণগঞ্জ সদর', 'name_en' => 'Narayanganj Sadar'],
                        ['slug' => 'bandar', 'name_bn' => 'বন্দর', 'name_en' => 'Bandar'],
                        ['slug' => 'araihazar', 'name_bn' => 'আড়াইহাজার', 'name_en' => 'Araihazar'],
                        ['slug' => 'rupganj', 'name_bn' => 'রূপগঞ্জ', 'name_en' => 'Rupganj'],
                        ['slug' => 'sonargaon', 'name_bn' => 'সোনারগাঁও', 'name_en' => 'Sonargaon'],
                    ]],
                    ['slug' => 'narsingdi', 'name_bn' => 'নরসিংদী', 'name_en' => 'Narsingdi', 'upazilas' => [
                        ['slug' => 'narsingdi-sadar', 'name_bn' => 'নরসিংদী সদর', 'name_en' => 'Narsingdi Sadar'],
                        ['slug' => 'belabo', 'name_bn' => 'বেলাবো', 'name_en' => 'Belabo'],
                        ['slug' => 'monohardi', 'name_bn' => 'মনোহরদী', 'name_en' => 'Monohardi'],
                        ['slug' => 'palash', 'name_bn' => 'পলাশ', 'name_en' => 'Palash'],
                        ['slug' => 'raipura', 'name_bn' => 'রায়পুরা', 'name_en' => 'Raipura'],
                        ['slug' => 'shibpur', 'name_bn' => 'শিবপুর', 'name_en' => 'Shibpur'],
                    ]],
                    ['slug' => 'manikganj', 'name_bn' => 'মানিকগঞ্জ', 'name_en' => 'Manikganj', 'upazilas' => [
                        ['slug' => 'manikganj-sadar', 'name_bn' => 'মানিকগঞ্জ সদর', 'name_en' => 'Manikganj Sadar'],
                        ['slug' => 'daulatpur', 'name_bn' => 'দৌলতপুর', 'name_en' => 'Daulatpur'],
                        ['slug' => 'ghior', 'name_bn' => 'ঘিওর', 'name_en' => 'Ghior'],
                        ['slug' => 'harirampur', 'name_bn' => 'হরিরামপুর', 'name_en' => 'Harirampur'],
                        ['slug' => 'saturia', 'name_bn' => 'সাটুরিয়া', 'name_en' => 'Saturia'],
                        ['slug' => 'shivalaya', 'name_bn' => 'শিবালয়', 'name_en' => 'Shivalaya'],
                        ['slug' => 'singair', 'name_bn' => 'সিংগাইর', 'name_en' => 'Singair'],
                    ]],
                    ['slug' => 'munshiganj', 'name_bn' => 'মুন্সীগঞ্জ', 'name_en' => 'Munshiganj', 'upazilas' => [
                        ['slug' => 'munshiganj-sadar', 'name_bn' => 'মুন্সীগঞ্জ সদর', 'name_en' => 'Munshiganj Sadar'],
                        ['slug' => 'gazaria', 'name_bn' => 'গজারিয়া', 'name_en' => 'Gazaria'],
                        ['slug' => 'lohajang', 'name_bn' => 'লৌহজং', 'name_en' => 'Lohajang'],
                        ['slug' => 'sirajdikhan', 'name_bn' => 'সিরাজদিখান', 'name_en' => 'Sirajdikhan'],
                        ['slug' => 'sreenagar', 'name_bn' => 'শ্রীনগর', 'name_en' => 'Sreenagar'],
                        ['slug' => 'tongibari', 'name_bn' => 'টংগিবাড়ী', 'name_en' => 'Tongibari'],
                    ]],
                    ['slug' => 'kishoreganj', 'name_bn' => 'কিশোরগঞ্জ', 'name_en' => 'Kishoreganj', 'upazilas' => [
                        ['slug' => 'kishoreganj-sadar', 'name_bn' => 'কিশোরগঞ্জ সদর', 'name_en' => 'Kishoreganj Sadar'],
                        ['slug' => 'austagram', 'name_bn' => 'অষ্টগ্রাম', 'name_en' => 'Austagram'],
                        ['slug' => 'bajitpur', 'name_bn' => 'বাজিতপুর', 'name_en' => 'Bajitpur'],
                        ['slug' => 'bhairab', 'name_bn' => 'ভৈরব', 'name_en' => 'Bhairab'],
                        ['slug' => 'hossainpur', 'name_bn' => 'হোসেনপুর', 'name_en' => 'Hossainpur'],
                        ['slug' => 'itna', 'name_bn' => 'ইটনা', 'name_en' => 'Itna'],
                        ['slug' => 'karimganj', 'name_bn' => 'করিমগঞ্জ', 'name_en' => 'Karimganj'],
                        ['slug' => 'katiadi', 'name_bn' => 'কটিয়াদী', 'name_en' => 'Katiadi'],
                        ['slug' => 'kuliarchar', 'name_bn' => 'কুলিয়ারচর', 'name_en' => 'Kuliarchar'],
                        ['slug' => 'mithamain', 'name_bn' => 'মিঠামইন', 'name_en' => 'Mithamain'],
                        ['slug' => 'nikli', 'name_bn' => 'নিকলী', 'name_en' => 'Nikli'],
                        ['slug' => 'pakundia', 'name_bn' => 'পাকুন্দিয়া', 'name_en' => 'Pakundia'],
                        ['slug' => 'tarail', 'name_bn' => 'তাড়াইল', 'name_en' => 'Tarail'],
                    ]],
                    ['slug' => 'tangail', 'name_bn' => 'টাঙ্গাইল', 'name_en' => 'Tangail', 'upazilas' => [
                        ['slug' => 'tangail-sadar', 'name_bn' => 'টাঙ্গাইল সদর', 'name_en' => 'Tangail Sadar'],
                        ['slug' => 'basail', 'name_bn' => 'বাসাইল', 'name_en' => 'Basail'],
                        ['slug' => 'bhuapur', 'name_bn' => 'ভূঞাপুর', 'name_en' => 'Bhuapur'],
                        ['slug' => 'delduar', 'name_bn' => 'দেলদুয়ার', 'name_en' => 'Delduar'],
                        ['slug' => 'dhanbari', 'name_bn' => 'ধনবাড়ী', 'name_en' => 'Dhanbari'],
                        ['slug' => 'ghatail', 'name_bn' => 'ঘাটাইল', 'name_en' => 'Ghatail'],
                        ['slug' => 'gopalpur', 'name_bn' => 'গোপালপুর', 'name_en' => 'Gopalpur'],
                        ['slug' => 'kalihati', 'name_bn' => 'কালিহাতী', 'name_en' => 'Kalihati'],
                        ['slug' => 'madhupur', 'name_bn' => 'মধুপুর', 'name_en' => 'Madhupur'],
                        ['slug' => 'mirzapur', 'name_bn' => 'মির্জাপুর', 'name_en' => 'Mirzapur'],
                        ['slug' => 'nagarpur', 'name_bn' => 'নাগরপুর', 'name_en' => 'Nagarpur'],
                        ['slug' => 'sakhipur', 'name_bn' => 'সখীপুর', 'name_en' => 'Sakhipur'],
                    ]],
                    ['slug' => 'faridpur', 'name_bn' => 'ফরিদপুর', 'name_en' => 'Faridpur', 'upazilas' => [
                        ['slug' => 'faridpur-sadar', 'name_bn' => 'ফরিদপুর সদর', 'name_en' => 'Faridpur Sadar'],
                        ['slug' => 'alfadanga', 'name_bn' => 'আলফাডাঙ্গা', 'name_en' => 'Alfadanga'],
                        ['slug' => 'bhanga', 'name_bn' => 'ভাঙ্গা', 'name_en' => 'Bhanga'],
                        ['slug' => 'boalmari', 'name_bn' => 'বোয়ালমারী', 'name_en' => 'Boalmari'],
                        ['slug' => 'charbhadrasan', 'name_bn' => 'চরভদ্রাসন', 'name_en' => 'Charbhadrasan'],
                        ['slug' => 'madhukhali', 'name_bn' => 'মধুখালী', 'name_en' => 'Madhukhali'],
                        ['slug' => 'nagarkanda', 'name_bn' => 'নগরকান্দা', 'name_en' => 'Nagarkanda'],
                        ['slug' => 'sadarpur', 'name_bn' => 'সদরপুর', 'name_en' => 'Sadarpur'],
                        ['slug' => 'saltha', 'name_bn' => 'সালথা', 'name_en' => 'Saltha'],
                    ]],
                    ['slug' => 'gopalganj', 'name_bn' => 'গোপালগঞ্জ', 'name_en' => 'Gopalganj', 'upazilas' => [
                        ['slug' => 'gopalganj-sadar', 'name_bn' => 'গোপালগঞ্জ সদর', 'name_en' => 'Gopalganj Sadar'],
                        ['slug' => 'kashiani', 'name_bn' => 'কাশিয়ানী', 'name_en' => 'Kashiani'],
                        ['slug' => 'kotalipara', 'name_bn' => 'কোটালীপাড়া', 'name_en' => 'Kotalipara'],
                        ['slug' => 'muksudpur', 'name_bn' => 'মুকসুদপুর', 'name_en' => 'Muksudpur'],
                        ['slug' => 'tungipara', 'name_bn' => 'টুঙ্গিপাড়া', 'name_en' => 'Tungipara'],
                    ]],
                    ['slug' => 'madaripur', 'name_bn' => 'মাদারীপুর', 'name_en' => 'Madaripur', 'upazilas' => [
                        ['slug' => 'madaripur-sadar', 'name_bn' => 'মাদারীপুর সদর', 'name_en' => 'Madaripur Sadar'],
                        ['slug' => 'kalkini', 'name_bn' => 'কালকিনি', 'name_en' => 'Kalkini'],
                        ['slug' => 'rajoir', 'name_bn' => 'রাজৈর', 'name_en' => 'Rajoir'],
                        ['slug' => 'shibchar', 'name_bn' => 'শিবচর', 'name_en' => 'Shibchar'],
                        ['slug' => 'dasar', 'name_bn' => 'ডাসার', 'name_en' => 'Dasar'],
                    ]],
                    ['slug' => 'rajbari', 'name_bn' => 'রাজবাড়ী', 'name_en' => 'Rajbari', 'upazilas' => [
                        ['slug' => 'rajbari-sadar', 'name_bn' => 'রাজবাড়ী সদর', 'name_en' => 'Rajbari Sadar'],
                        ['slug' => 'baliakandi', 'name_bn' => 'বালিয়াকান্দি', 'name_en' => 'Baliakandi'],
                        ['slug' => 'goalanda', 'name_bn' => 'গোয়ালন্দ', 'name_en' => 'Goalanda'],
                        ['slug' => 'kalukhali', 'name_bn' => 'কালুখালী', 'name_en' => 'Kalukhali'],
                        ['slug' => 'pangsha', 'name_bn' => 'পাংশা', 'name_en' => 'Pangsha'],
                    ]],
                    ['slug' => 'shariatpur', 'name_bn' => 'শরীয়তপুর', 'name_en' => 'Shariatpur', 'upazilas' => [
                        ['slug' => 'shariatpur-sadar', 'name_bn' => 'শরীয়তপুর সদর', 'name_en' => 'Shariatpur Sadar'],
                        ['slug' => 'bhedarganj', 'name_bn' => 'ভেদরগঞ্জ', 'name_en' => 'Bhedarganj'],
                        ['slug' => 'damudya', 'name_bn' => 'ডামুড্যা', 'name_en' => 'Damudya'],
                        ['slug' => 'gosairhat', 'name_bn' => 'গোসাইরহাট', 'name_en' => 'Gosairhat'],
                        ['slug' => 'naria', 'name_bn' => 'নড়িয়া', 'name_en' => 'Naria'],
                        ['slug' => 'zajira', 'name_bn' => 'জাজিরা', 'name_en' => 'Zajira'],
                    ]],
                ],
            ],
            [
                'slug' => 'chittagong', 'name_bn' => 'চট্টগ্রাম', 'name_en' => 'Chittagong',
                'districts' => [
                    ['slug' => 'chittagong', 'name_bn' => 'চট্টগ্রাম', 'name_en' => 'Chittagong', 'upazilas' => [
                        ['slug' => 'anwara', 'name_bn' => 'আনোয়ারা', 'name_en' => 'Anwara'],
                        ['slug' => 'banshkhali', 'name_bn' => 'বাঁশখালী', 'name_en' => 'Banshkhali'],
                        ['slug' => 'boalkhali', 'name_bn' => 'বোয়ালখালী', 'name_en' => 'Boalkhali'],
                        ['slug' => 'chandanaish', 'name_bn' => 'চন্দনাইশ', 'name_en' => 'Chandanaish'],
                        ['slug' => 'fatikchhari', 'name_bn' => 'ফটিকছড়ি', 'name_en' => 'Fatikchhari'],
                        ['slug' => 'hathazari', 'name_bn' => 'হাটহাজারী', 'name_en' => 'Hathazari'],
                        ['slug' => 'kotwali', 'name_bn' => 'কোতোয়ালি', 'name_en' => 'Kotwali'],
                        ['slug' => 'lohagara', 'name_bn' => 'লোহাগাড়া', 'name_en' => 'Lohagara'],
                        ['slug' => 'mirsharai', 'name_bn' => 'মীরসরাই', 'name_en' => 'Mirsharai'],
                        ['slug' => 'patiya', 'name_bn' => 'পটিয়া', 'name_en' => 'Patiya'],
                        ['slug' => 'rangunia', 'name_bn' => 'রাঙ্গুনিয়া', 'name_en' => 'Rangunia'],
                        ['slug' => 'raozan', 'name_bn' => 'রাউজান', 'name_en' => 'Raozan'],
                        ['slug' => 'sandwip', 'name_bn' => 'সন্দ্বীপ', 'name_en' => 'Sandwip'],
                        ['slug' => 'satkania', 'name_bn' => 'সাতকানিয়া', 'name_en' => 'Satkania'],
                        ['slug' => 'sitakunda', 'name_bn' => 'সীতাকুণ্ড', 'name_en' => 'Sitakunda'],
                    ]],
                    ['slug' => 'cox-bazar', 'name_bn' => 'কক্সবাজার', 'name_en' => "Cox's Bazar", 'upazilas' => [
                        ['slug' => 'chakaria', 'name_bn' => 'চকরিয়া', 'name_en' => 'Chakaria'],
                        ['slug' => 'coxs-bazar-sadar', 'name_bn' => 'কক্সবাজার সদর', 'name_en' => "Cox's Bazar Sadar"],
                        ['slug' => 'kutubdia', 'name_bn' => 'কুতুবদিয়া', 'name_en' => 'Kutubdia'],
                        ['slug' => 'maheshkhali', 'name_bn' => 'মহেশখালী', 'name_en' => 'Maheshkhali'],
                        ['slug' => 'pekua', 'name_bn' => 'পেকুয়া', 'name_en' => 'Pekua'],
                        ['slug' => 'ramu', 'name_bn' => 'রামু', 'name_en' => 'Ramu'],
                        ['slug' => 'teknaf', 'name_bn' => 'টেকনাফ', 'name_en' => 'Teknaf'],
                        ['slug' => 'ukhia', 'name_bn' => 'উখিয়া', 'name_en' => 'Ukhia'],
                    ]],
                    ['slug' => 'comilla', 'name_bn' => 'কুমিল্লা', 'name_en' => 'Comilla', 'upazilas' => [
                        ['slug' => 'comilla-sadar', 'name_bn' => 'কুমিল্লা সদর', 'name_en' => 'Comilla Sadar'],
                        ['slug' => 'barura', 'name_bn' => 'বরুড়া', 'name_en' => 'Barura'],
                        ['slug' => 'brahmanpara', 'name_bn' => 'ব্রাহ্মণপাড়া', 'name_en' => 'Brahmanpara'],
                        ['slug' => 'burichang', 'name_bn' => 'বুড়িচং', 'name_en' => 'Burichang'],
                        ['slug' => 'chandina', 'name_bn' => 'চান্দিনা', 'name_en' => 'Chandina'],
                        ['slug' => 'chauddagram', 'name_bn' => 'চৌদ্দগ্রাম', 'name_en' => 'Chauddagram'],
                        ['slug' => 'daudkandi', 'name_bn' => 'দাউদকান্দি', 'name_en' => 'Daudkandi'],
                        ['slug' => 'debidwar', 'name_bn' => 'দেবীদ্বার', 'name_en' => 'Debidwar'],
                        ['slug' => 'homna', 'name_bn' => 'হোমনা', 'name_en' => 'Homna'],
                        ['slug' => 'laksam', 'name_bn' => 'লাকসাম', 'name_en' => 'Laksam'],
                        ['slug' => 'langalkot', 'name_bn' => 'লাঙ্গলকোট', 'name_en' => 'Langalkot'],
                        ['slug' => 'meghna', 'name_bn' => 'মেঘনা', 'name_en' => 'Meghna'],
                        ['slug' => 'monohorgonj', 'name_bn' => 'মনোহরগঞ্জ', 'name_en' => 'Monohorgonj'],
                        ['slug' => 'muradnagar', 'name_bn' => 'মুরাদনগর', 'name_en' => 'Muradnagar'],
                        ['slug' => 'nangalkot', 'name_bn' => 'নাঙ্গলকোট', 'name_en' => 'Nangalkot'],
                        ['slug' => 'titas', 'name_bn' => 'তিতাস', 'name_en' => 'Titas'],
                    ]],
                    ['slug' => 'chandpur', 'name_bn' => 'চাঁদপুর', 'name_en' => 'Chandpur', 'upazilas' => [
                        ['slug' => 'chandpur-sadar', 'name_bn' => 'চাঁদপুর সদর', 'name_en' => 'Chandpur Sadar'],
                        ['slug' => 'faridganj', 'name_bn' => 'ফরিদগঞ্জ', 'name_en' => 'Faridganj'],
                        ['slug' => 'haimchar', 'name_bn' => 'হাইমচর', 'name_en' => 'Haimchar'],
                        ['slug' => 'hajiganj', 'name_bn' => 'হাজীগঞ্জ', 'name_en' => 'Hajiganj'],
                        ['slug' => 'kachua', 'name_bn' => 'কচুয়া', 'name_en' => 'Kachua'],
                        ['slug' => 'matlab-north', 'name_bn' => 'মতলব উত্তর', 'name_en' => 'Matlab North'],
                        ['slug' => 'matlab-south', 'name_bn' => 'মতলব দক্ষিণ', 'name_en' => 'Matlab South'],
                        ['slug' => 'shahrasti', 'name_bn' => 'শাহরাস্তি', 'name_en' => 'Shahrasti'],
                    ]],
                    ['slug' => 'feni', 'name_bn' => 'ফেনী', 'name_en' => 'Feni', 'upazilas' => [
                        ['slug' => 'feni-sadar', 'name_bn' => 'ফেনী সদর', 'name_en' => 'Feni Sadar'],
                        ['slug' => 'chhagalnaiya', 'name_bn' => 'ছাগলনাইয়া', 'name_en' => 'Chhagalnaiya'],
                        ['slug' => 'daganbhuiyan', 'name_bn' => 'দাগনভূঞা', 'name_en' => 'Daganbhuiyan'],
                        ['slug' => 'parshuram', 'name_bn' => 'পরশুরাম', 'name_en' => 'Parshuram'],
                        ['slug' => 'sonagazi', 'name_bn' => 'সোনাগাজী', 'name_en' => 'Sonagazi'],
                    ]],
                    ['slug' => 'noakhali', 'name_bn' => 'নোয়াখালী', 'name_en' => 'Noakhali', 'upazilas' => [
                        ['slug' => 'begumganj', 'name_bn' => 'বেগমগঞ্জ', 'name_en' => 'Begumganj'],
                        ['slug' => 'chatkhil', 'name_bn' => 'চাটখিল', 'name_en' => 'Chatkhil'],
                        ['slug' => 'companiganj', 'name_bn' => 'কোম্পানিগঞ্জ', 'name_en' => 'Companiganj'],
                        ['slug' => 'hatiya', 'name_bn' => 'হাতিয়া', 'name_en' => 'Hatiya'],
                        ['slug' => 'kabirhat', 'name_bn' => 'কবিরহাট', 'name_en' => 'Kabirhat'],
                        ['slug' => 'noakhali-sadar', 'name_bn' => 'নোয়াখালী সদর', 'name_en' => 'Noakhali Sadar'],
                        ['slug' => 'senbagh', 'name_bn' => 'সেনবাগ', 'name_en' => 'Senbagh'],
                        ['slug' => 'subarnachar', 'name_bn' => 'সুবর্ণচর', 'name_en' => 'Subarnachar'],
                    ]],
                    ['slug' => 'lakshmipur', 'name_bn' => 'লক্ষ্মীপুর', 'name_en' => 'Lakshmipur', 'upazilas' => [
                        ['slug' => 'lakshmipur-sadar', 'name_bn' => 'লক্ষ্মীপুর সদর', 'name_en' => 'Lakshmipur Sadar'],
                        ['slug' => 'kamalnagar', 'name_bn' => 'কমলনগর', 'name_en' => 'Kamalnagar'],
                        ['slug' => 'raipur', 'name_bn' => 'রায়পুর', 'name_en' => 'Raipur'],
                        ['slug' => 'ramganj', 'name_bn' => 'রামগঞ্জ', 'name_en' => 'Ramganj'],
                        ['slug' => 'ramgati', 'name_bn' => 'রামগতি', 'name_en' => 'Ramgati'],
                    ]],
                    ['slug' => 'brahmanbaria', 'name_bn' => 'ব্রাহ্মণবাড়িয়া', 'name_en' => 'Brahmanbaria', 'upazilas' => [
                        ['slug' => 'brahmanbaria-sadar', 'name_bn' => 'ব্রাহ্মণবাড়িয়া সদর', 'name_en' => 'Brahmanbaria Sadar'],
                        ['slug' => 'akhaura', 'name_bn' => 'আখাউড়া', 'name_en' => 'Akhaura'],
                        ['slug' => 'ashuganj', 'name_bn' => 'আশুগঞ্জ', 'name_en' => 'Ashuganj'],
                        ['slug' => 'bancharampur', 'name_bn' => 'বাঞ্ছারামপুর', 'name_en' => 'Bancharampur'],
                        ['slug' => 'bijoynagar', 'name_bn' => 'বিজয়নগর', 'name_en' => 'Bijoynagar'],
                        ['slug' => 'kasba', 'name_bn' => 'কসবা', 'name_en' => 'Kasba'],
                        ['slug' => 'nabinagar', 'name_bn' => 'নবীনগর', 'name_en' => 'Nabinagar'],
                        ['slug' => 'nasirnagar', 'name_bn' => 'নাসিরনগর', 'name_en' => 'Nasirnagar'],
                        ['slug' => 'sarail', 'name_bn' => 'সরাইল', 'name_en' => 'Sarail'],
                    ]],
                    ['slug' => 'bandarban', 'name_bn' => 'বান্দরবান', 'name_en' => 'Bandarban', 'upazilas' => [
                        ['slug' => 'bandarban-sadar', 'name_bn' => 'বান্দরবান সদর', 'name_en' => 'Bandarban Sadar'],
                        ['slug' => 'alikadam', 'name_bn' => 'আলীকদম', 'name_en' => 'Alikadam'],
                        ['slug' => 'lama', 'name_bn' => 'লামা', 'name_en' => 'Lama'],
                        ['slug' => 'naikhongchhari', 'name_bn' => 'নাইক্ষ্যংছড়ি', 'name_en' => 'Naikhongchhari'],
                        ['slug' => 'rowangchhari', 'name_bn' => 'রোয়াংছড়ি', 'name_en' => 'Rowangchhari'],
                        ['slug' => 'ruma', 'name_bn' => 'রুমা', 'name_en' => 'Ruma'],
                        ['slug' => 'thanchi', 'name_bn' => 'থানচি', 'name_en' => 'Thanchi'],
                    ]],
                    ['slug' => 'khagrachhari', 'name_bn' => 'খাগড়াছড়ি', 'name_en' => 'Khagrachhari', 'upazilas' => [
                        ['slug' => 'khagrachhari-sadar', 'name_bn' => 'খাগড়াছড়ি সদর', 'name_en' => 'Khagrachhari Sadar'],
                        ['slug' => 'dighinala', 'name_bn' => 'দীঘিনালা', 'name_en' => 'Dighinala'],
                        ['slug' => 'guimara', 'name_bn' => 'গুইমারা', 'name_en' => 'Guimara'],
                        ['slug' => 'lakshmichhari', 'name_bn' => 'লক্ষ্মীছড়ি', 'name_en' => 'Lakshmichhari'],
                        ['slug' => 'mahalchhari', 'name_bn' => 'মহালছড়ি', 'name_en' => 'Mahalchhari'],
                        ['slug' => 'manikchhari', 'name_bn' => 'মানিকছড়ি', 'name_en' => 'Manikchhari'],
                        ['slug' => 'matiranga', 'name_bn' => 'মাটিরাঙ্গা', 'name_en' => 'Matiranga'],
                        ['slug' => 'panchhari', 'name_bn' => 'পানছড়ি', 'name_en' => 'Panchhari'],
                        ['slug' => 'ramgarh', 'name_bn' => 'রামগড়', 'name_en' => 'Ramgarh'],
                    ]],
                    ['slug' => 'rangamati', 'name_bn' => 'রাঙ্গামাটি', 'name_en' => 'Rangamati', 'upazilas' => [
                        ['slug' => 'rangamati-sadar', 'name_bn' => 'রাঙ্গামাটি সদর', 'name_en' => 'Rangamati Sadar'],
                        ['slug' => 'baghaichhari', 'name_bn' => 'বাঘাইছড়ি', 'name_en' => 'Baghaichhari'],
                        ['slug' => 'barkal', 'name_bn' => 'বরকল', 'name_en' => 'Barkal'],
                        ['slug' => 'belaichhari', 'name_bn' => 'বেলাইছড়ি', 'name_en' => 'Belaichhari'],
                        ['slug' => 'juraichhari', 'name_bn' => 'জুরাছড়ি', 'name_en' => 'Juraichhari'],
                        ['slug' => 'kaptai', 'name_bn' => 'কাপ্তাই', 'name_en' => 'Kaptai'],
                        ['slug' => 'kaukhali-rangamati', 'name_bn' => 'কাউখালী', 'name_en' => 'Kaukhali'],
                        ['slug' => 'langadu', 'name_bn' => 'লংগদু', 'name_en' => 'Langadu'],
                        ['slug' => 'naniarchar', 'name_bn' => 'নানিয়ারচর', 'name_en' => 'Naniarchar'],
                        ['slug' => 'rajasthali', 'name_bn' => 'রাজস্থলী', 'name_en' => 'Rajasthali'],
                    ]],
                ],
            ],
            [
                'slug' => 'rajshahi', 'name_bn' => 'রাজশাহী', 'name_en' => 'Rajshahi',
                'districts' => [
                    ['slug' => 'rajshahi', 'name_bn' => 'রাজশাহী', 'name_en' => 'Rajshahi', 'upazilas' => [
                        ['slug' => 'bagha', 'name_bn' => 'বাঘা', 'name_en' => 'Bagha'],
                        ['slug' => 'bagmara', 'name_bn' => 'বাগমারা', 'name_en' => 'Bagmara'],
                        ['slug' => 'charghat', 'name_bn' => 'চারঘাট', 'name_en' => 'Charghat'],
                        ['slug' => 'durgapur', 'name_bn' => 'দুর্গাপুর', 'name_en' => 'Durgapur'],
                        ['slug' => 'godagari', 'name_bn' => 'গোদাগাড়ী', 'name_en' => 'Godagari'],
                        ['slug' => 'mohanpur', 'name_bn' => 'মোহনপুর', 'name_en' => 'Mohanpur'],
                        ['slug' => 'paba', 'name_bn' => 'পবা', 'name_en' => 'Paba'],
                        ['slug' => 'puthia', 'name_bn' => 'পুঠিয়া', 'name_en' => 'Puthia'],
                        ['slug' => 'tanore', 'name_bn' => 'তানোর', 'name_en' => 'Tanore'],
                    ]],
                    ['slug' => 'bogura', 'name_bn' => 'বগুড়া', 'name_en' => 'Bogura', 'upazilas' => [
                        ['slug' => 'bogura-sadar', 'name_bn' => 'বগুড়া সদর', 'name_en' => 'Bogura Sadar'],
                        ['slug' => 'adamdighi', 'name_bn' => 'আদমদীঘি', 'name_en' => 'Adamdighi'],
                        ['slug' => 'dhunat', 'name_bn' => 'ধুনট', 'name_en' => 'Dhunat'],
                        ['slug' => 'dupchanchia', 'name_bn' => 'দুপচাঁচিয়া', 'name_en' => 'Dupchanchia'],
                        ['slug' => 'gabtali', 'name_bn' => 'গাবতলী', 'name_en' => 'Gabtali'],
                        ['slug' => 'kahaloo', 'name_bn' => 'কাহালু', 'name_en' => 'Kahaloo'],
                        ['slug' => 'nandigram', 'name_bn' => 'নন্দীগ্রাম', 'name_en' => 'Nandigram'],
                        ['slug' => 'sariakandi', 'name_bn' => 'সারিয়াকান্দি', 'name_en' => 'Sariakandi'],
                        ['slug' => 'shajahanpur', 'name_bn' => 'শাজাহানপুর', 'name_en' => 'Shajahanpur'],
                        ['slug' => 'sherpur-bogura', 'name_bn' => 'শেরপুর', 'name_en' => 'Sherpur'],
                        ['slug' => 'shibganj-bogura', 'name_bn' => 'শিবগঞ্জ', 'name_en' => 'Shibganj'],
                        ['slug' => 'sonatala', 'name_bn' => 'সোনাতলা', 'name_en' => 'Sonatala'],
                    ]],
                    ['slug' => 'chapainawabganj', 'name_bn' => 'চাঁপাইনবাবগঞ্জ', 'name_en' => 'Chapainawabganj', 'upazilas' => [
                        ['slug' => 'chapainawabganj-sadar', 'name_bn' => 'চাঁপাইনবাবগঞ্জ সদর', 'name_en' => 'Chapainawabganj Sadar'],
                        ['slug' => 'gomastapur', 'name_bn' => 'গোমস্তাপুর', 'name_en' => 'Gomastapur'],
                        ['slug' => 'nachole', 'name_bn' => 'নাচোল', 'name_en' => 'Nachole'],
                        ['slug' => 'shibganj-chapai', 'name_bn' => 'শিবগঞ্জ', 'name_en' => 'Shibganj'],
                        ['slug' => 'bholahat', 'name_bn' => 'ভোলাহাট', 'name_en' => 'Bholahat'],
                    ]],
                    ['slug' => 'naogaon', 'name_bn' => 'নওগাঁ', 'name_en' => 'Naogaon', 'upazilas' => [
                        ['slug' => 'naogaon-sadar', 'name_bn' => 'নওগাঁ সদর', 'name_en' => 'Naogaon Sadar'],
                        ['slug' => 'atrai', 'name_bn' => 'আত্রাই', 'name_en' => 'Atrai'],
                        ['slug' => 'badalgachhi', 'name_bn' => 'বাদলগাছী', 'name_en' => 'Badalgachhi'],
                        ['slug' => 'dhamoirhat', 'name_bn' => 'ধামইরহাট', 'name_en' => 'Dhamoirhat'],
                        ['slug' => 'manda', 'name_bn' => 'মান্দা', 'name_en' => 'Manda'],
                        ['slug' => 'mahadebpur', 'name_bn' => 'মহাদেবপুর', 'name_en' => 'Mahadebpur'],
                        ['slug' => 'niamatpur', 'name_bn' => 'নিয়ামতপুর', 'name_en' => 'Niamatpur'],
                        ['slug' => 'patnitala', 'name_bn' => 'পত্নীতলা', 'name_en' => 'Patnitala'],
                        ['slug' => 'porsha', 'name_bn' => 'পোরশা', 'name_en' => 'Porsha'],
                        ['slug' => 'raninagar', 'name_bn' => 'রাণীনগর', 'name_en' => 'Raninagar'],
                        ['slug' => 'sapahar', 'name_bn' => 'সাপাহার', 'name_en' => 'Sapahar'],
                    ]],
                    ['slug' => 'natore', 'name_bn' => 'নাটোর', 'name_en' => 'Natore', 'upazilas' => [
                        ['slug' => 'natore-sadar', 'name_bn' => 'নাটোর সদর', 'name_en' => 'Natore Sadar'],
                        ['slug' => 'bagatipara', 'name_bn' => 'বাগাতিপাড়া', 'name_en' => 'Bagatipara'],
                        ['slug' => 'baraigram', 'name_bn' => 'বড়াইগ্রাম', 'name_en' => 'Baraigram'],
                        ['slug' => 'gurudaspur', 'name_bn' => 'গুরুদাসপুর', 'name_en' => 'Gurudaspur'],
                        ['slug' => 'lalpur', 'name_bn' => 'লালপুর', 'name_en' => 'Lalpur'],
                        ['slug' => 'singra', 'name_bn' => 'সিংড়া', 'name_en' => 'Singra'],
                    ]],
                    ['slug' => 'pabna', 'name_bn' => 'পাবনা', 'name_en' => 'Pabna', 'upazilas' => [
                        ['slug' => 'pabna-sadar', 'name_bn' => 'পাবনা সদর', 'name_en' => 'Pabna Sadar'],
                        ['slug' => 'atgharia', 'name_bn' => 'আটঘরিয়া', 'name_en' => 'Atgharia'],
                        ['slug' => 'bera', 'name_bn' => 'বেড়া', 'name_en' => 'Bera'],
                        ['slug' => 'bhangura', 'name_bn' => 'ভাঙ্গুড়া', 'name_en' => 'Bhangura'],
                        ['slug' => 'chatmohar', 'name_bn' => 'চাটমোহর', 'name_en' => 'Chatmohar'],
                        ['slug' => 'faridpur-pabna', 'name_bn' => 'ফরিদপুর', 'name_en' => 'Faridpur'],
                        ['slug' => 'ishwardi', 'name_bn' => 'ঈশ্বরদী', 'name_en' => 'Ishwardi'],
                        ['slug' => 'santhia', 'name_bn' => 'সাঁথিয়া', 'name_en' => 'Santhia'],
                        ['slug' => 'sujanagar', 'name_bn' => 'সুজানগর', 'name_en' => 'Sujanagar'],
                    ]],
                    ['slug' => 'sirajganj', 'name_bn' => 'সিরাজগঞ্জ', 'name_en' => 'Sirajganj', 'upazilas' => [
                        ['slug' => 'sirajganj-sadar', 'name_bn' => 'সিরাজগঞ্জ সদর', 'name_en' => 'Sirajganj Sadar'],
                        ['slug' => 'belkuchi', 'name_bn' => 'বেলকুচি', 'name_en' => 'Belkuchi'],
                        ['slug' => 'chauhali', 'name_bn' => 'চৌহালি', 'name_en' => 'Chauhali'],
                        ['slug' => 'kamarkhand', 'name_bn' => 'কামারখন্দ', 'name_en' => 'Kamarkhand'],
                        ['slug' => 'kazipur', 'name_bn' => 'কাজীপুর', 'name_en' => 'Kazipur'],
                        ['slug' => 'raiganj', 'name_bn' => 'রায়গঞ্জ', 'name_en' => 'Raiganj'],
                        ['slug' => 'shahjadpur', 'name_bn' => 'শাহজাদপুর', 'name_en' => 'Shahjadpur'],
                        ['slug' => 'tarash', 'name_bn' => 'তাড়াশ', 'name_en' => 'Tarash'],
                        ['slug' => 'ullahpara', 'name_bn' => 'উল্লাপাড়া', 'name_en' => 'Ullahpara'],
                    ]],
                    ['slug' => 'joypurhat', 'name_bn' => 'জয়পুরহাট', 'name_en' => 'Joypurhat', 'upazilas' => [
                        ['slug' => 'joypurhat-sadar', 'name_bn' => 'জয়পুরহাট সদর', 'name_en' => 'Joypurhat Sadar'],
                        ['slug' => 'akkelpur', 'name_bn' => 'আক্কেলপুর', 'name_en' => 'Akkelpur'],
                        ['slug' => 'kalai', 'name_bn' => 'কালাই', 'name_en' => 'Kalai'],
                        ['slug' => 'khetlal', 'name_bn' => 'ক্ষেতলাল', 'name_en' => 'Khetlal'],
                        ['slug' => 'panchbibi', 'name_bn' => 'পাঁচবিবি', 'name_en' => 'Panchbibi'],
                    ]],
                ],
            ],
            [
                'slug' => 'khulna', 'name_bn' => 'খুলনা', 'name_en' => 'Khulna',
                'districts' => [
                    ['slug' => 'khulna', 'name_bn' => 'খুলনা', 'name_en' => 'Khulna', 'upazilas' => [
                        ['slug' => 'batiaghata', 'name_bn' => 'বটিয়াঘাটা', 'name_en' => 'Batiaghata'],
                        ['slug' => 'dacope', 'name_bn' => 'দাকোপ', 'name_en' => 'Dacope'],
                        ['slug' => 'dumuria', 'name_bn' => 'ডুমুরিয়া', 'name_en' => 'Dumuria'],
                        ['slug' => 'dighalia', 'name_bn' => 'দীঘলিয়া', 'name_en' => 'Dighalia'],
                        ['slug' => 'koyra', 'name_bn' => 'কয়রা', 'name_en' => 'Koyra'],
                        ['slug' => 'paikgachha', 'name_bn' => 'পাইকগাছা', 'name_en' => 'Paikgachha'],
                        ['slug' => 'phultala', 'name_bn' => 'ফুলতলা', 'name_en' => 'Phultala'],
                        ['slug' => 'rupsa', 'name_bn' => 'রূপসা', 'name_en' => 'Rupsa'],
                        ['slug' => 'terokhada', 'name_bn' => 'তেরখাদা', 'name_en' => 'Terokhada'],
                    ]],
                    ['slug' => 'jessore', 'name_bn' => 'যশোর', 'name_en' => 'Jessore', 'upazilas' => [
                        ['slug' => 'jessore-sadar', 'name_bn' => 'যশোর সদর', 'name_en' => 'Jessore Sadar'],
                        ['slug' => 'abhaynagar', 'name_bn' => 'অভয়নগর', 'name_en' => 'Abhaynagar'],
                        ['slug' => 'bagherpara', 'name_bn' => 'বাঘেরপাড়া', 'name_en' => 'Bagherpara'],
                        ['slug' => 'chaugachha', 'name_bn' => 'চৌগাছা', 'name_en' => 'Chaugachha'],
                        ['slug' => 'jhikargachha', 'name_bn' => 'ঝিকরগাছা', 'name_en' => 'Jhikargachha'],
                        ['slug' => 'keshabpur', 'name_bn' => 'কেশবপুর', 'name_en' => 'Keshabpur'],
                        ['slug' => 'manirampur', 'name_bn' => 'মণিরামপুর', 'name_en' => 'Manirampur'],
                        ['slug' => 'sharsha', 'name_bn' => 'শার্শা', 'name_en' => 'Sharsha'],
                    ]],
                    ['slug' => 'bagerhat', 'name_bn' => 'বাগেরহাট', 'name_en' => 'Bagerhat', 'upazilas' => [
                        ['slug' => 'bagerhat-sadar', 'name_bn' => 'বাগেরহাট সদর', 'name_en' => 'Bagerhat Sadar'],
                        ['slug' => 'chitalmari', 'name_bn' => 'চিতলমারী', 'name_en' => 'Chitalmari'],
                        ['slug' => 'fakirhat', 'name_bn' => 'ফকিরহাট', 'name_en' => 'Fakirhat'],
                        ['slug' => 'kachua-bagerhat', 'name_bn' => 'কচুয়া', 'name_en' => 'Kachua'],
                        ['slug' => 'mollahat', 'name_bn' => 'মোল্লাহাট', 'name_en' => 'Mollahat'],
                        ['slug' => 'mongla', 'name_bn' => 'মোংলা', 'name_en' => 'Mongla'],
                        ['slug' => 'morrelganj', 'name_bn' => 'মোড়েলগঞ্জ', 'name_en' => 'Morrelganj'],
                        ['slug' => 'rampal', 'name_bn' => 'রামপাল', 'name_en' => 'Rampal'],
                        ['slug' => 'sarankhola', 'name_bn' => 'শরণখোলা', 'name_en' => 'Sarankhola'],
                    ]],
                    ['slug' => 'satkhira', 'name_bn' => 'সাতক্ষীরা', 'name_en' => 'Satkhira', 'upazilas' => [
                        ['slug' => 'satkhira-sadar', 'name_bn' => 'সাতক্ষীরা সদর', 'name_en' => 'Satkhira Sadar'],
                        ['slug' => 'assasuni', 'name_bn' => 'আশাশুনি', 'name_en' => 'Assasuni'],
                        ['slug' => 'debhata', 'name_bn' => 'দেবহাটা', 'name_en' => 'Debhata'],
                        ['slug' => 'kalaroa', 'name_bn' => 'কলারোয়া', 'name_en' => 'Kalaroa'],
                        ['slug' => 'kaliganj-satkhira', 'name_bn' => 'কালিগঞ্জ', 'name_en' => 'Kaliganj'],
                        ['slug' => 'shyamnagar', 'name_bn' => 'শ্যামনগর', 'name_en' => 'Shyamnagar'],
                        ['slug' => 'tala', 'name_bn' => 'তালা', 'name_en' => 'Tala'],
                    ]],
                    ['slug' => 'magura', 'name_bn' => 'মাগুরা', 'name_en' => 'Magura', 'upazilas' => [
                        ['slug' => 'magura-sadar', 'name_bn' => 'মাগুরা সদর', 'name_en' => 'Magura Sadar'],
                        ['slug' => 'mohammadpur-magura', 'name_bn' => 'মোহাম্মদপুর', 'name_en' => 'Mohammadpur'],
                        ['slug' => 'shalikha', 'name_bn' => 'শালিখা', 'name_en' => 'Shalikha'],
                        ['slug' => 'sreepur-magura', 'name_bn' => 'শ্রীপুর', 'name_en' => 'Sreepur'],
                    ]],
                    ['slug' => 'narail', 'name_bn' => 'নড়াইল', 'name_en' => 'Narail', 'upazilas' => [
                        ['slug' => 'narail-sadar', 'name_bn' => 'নড়াইল সদর', 'name_en' => 'Narail Sadar'],
                        ['slug' => 'kalia', 'name_bn' => 'কালিয়া', 'name_en' => 'Kalia'],
                        ['slug' => 'lohagara-narail', 'name_bn' => 'লোহাগড়া', 'name_en' => 'Lohagara'],
                    ]],
                    ['slug' => 'kushtia', 'name_bn' => 'কুষ্টিয়া', 'name_en' => 'Kushtia', 'upazilas' => [
                        ['slug' => 'kushtia-sadar', 'name_bn' => 'কুষ্টিয়া সদর', 'name_en' => 'Kushtia Sadar'],
                        ['slug' => 'bheramara', 'name_bn' => 'ভেড়ামারা', 'name_en' => 'Bheramara'],
                        ['slug' => 'daulatpur-kushtia', 'name_bn' => 'দৌলতপুর', 'name_en' => 'Daulatpur'],
                        ['slug' => 'khoksa', 'name_bn' => 'খোকসা', 'name_en' => 'Khoksa'],
                        ['slug' => 'kumarkhali', 'name_bn' => 'কুমারখালী', 'name_en' => 'Kumarkhali'],
                        ['slug' => 'mirpur-kushtia', 'name_bn' => 'মিরপুর', 'name_en' => 'Mirpur'],
                    ]],
                    ['slug' => 'meherpur', 'name_bn' => 'মেহেরপুর', 'name_en' => 'Meherpur', 'upazilas' => [
                        ['slug' => 'meherpur-sadar', 'name_bn' => 'মেহেরপুর সদর', 'name_en' => 'Meherpur Sadar'],
                        ['slug' => 'gangni', 'name_bn' => 'গাংনী', 'name_en' => 'Gangni'],
                        ['slug' => 'mujibnagar', 'name_bn' => 'মুজিবনগর', 'name_en' => 'Mujibnagar'],
                    ]],
                    ['slug' => 'chuadanga', 'name_bn' => 'চুয়াডাঙ্গা', 'name_en' => 'Chuadanga', 'upazilas' => [
                        ['slug' => 'chuadanga-sadar', 'name_bn' => 'চুয়াডাঙ্গা সদর', 'name_en' => 'Chuadanga Sadar'],
                        ['slug' => 'alamdanga', 'name_bn' => 'আলমডাঙ্গা', 'name_en' => 'Alamdanga'],
                        ['slug' => 'damurhuda', 'name_bn' => 'দামুড়হুদা', 'name_en' => 'Damurhuda'],
                        ['slug' => 'jibannagar', 'name_bn' => 'জীবননগর', 'name_en' => 'Jibannagar'],
                    ]],
                    ['slug' => 'jhenaidah', 'name_bn' => 'ঝিনাইদহ', 'name_en' => 'Jhenaidah', 'upazilas' => [
                        ['slug' => 'jhenaidah-sadar', 'name_bn' => 'ঝিনাইদহ সদর', 'name_en' => 'Jhenaidah Sadar'],
                        ['slug' => 'harinakunda', 'name_bn' => 'হরিণাকুণ্ডু', 'name_en' => 'Harinakunda'],
                        ['slug' => 'kaliganj-jhenaidah', 'name_bn' => 'কালীগঞ্জ', 'name_en' => 'Kaliganj'],
                        ['slug' => 'kotchandpur', 'name_bn' => 'কোটচাঁদপুর', 'name_en' => 'Kotchandpur'],
                        ['slug' => 'maheshpur', 'name_bn' => 'মহেশপুর', 'name_en' => 'Maheshpur'],
                        ['slug' => 'shailkupa', 'name_bn' => 'শৈলকুপা', 'name_en' => 'Shailkupa'],
                    ]],
                ],
            ],
            [
                'slug' => 'barishal', 'name_bn' => 'বরিশাল', 'name_en' => 'Barishal',
                'districts' => [
                    ['slug' => 'barishal', 'name_bn' => 'বরিশাল', 'name_en' => 'Barishal', 'upazilas' => [
                        ['slug' => 'agailjhara', 'name_bn' => 'আগৈলঝাড়া', 'name_en' => 'Agailjhara'],
                        ['slug' => 'babuganj', 'name_bn' => 'বাবুগঞ্জ', 'name_en' => 'Babuganj'],
                        ['slug' => 'bakerganj', 'name_bn' => 'বাকেরগঞ্জ', 'name_en' => 'Bakerganj'],
                        ['slug' => 'banaripara', 'name_bn' => 'বানারীপাড়া', 'name_en' => 'Banaripara'],
                        ['slug' => 'gaurnadi', 'name_bn' => 'গৌরনদী', 'name_en' => 'Gaurnadi'],
                        ['slug' => 'hizla', 'name_bn' => 'হিজলা', 'name_en' => 'Hizla'],
                        ['slug' => 'mehendiganj', 'name_bn' => 'মেহেন্দিগঞ্জ', 'name_en' => 'Mehendiganj'],
                        ['slug' => 'muladi', 'name_bn' => 'মুলাদী', 'name_en' => 'Muladi'],
                        ['slug' => 'wazirpur', 'name_bn' => 'উজিরপুর', 'name_en' => 'Wazirpur'],
                    ]],
                    ['slug' => 'bhola', 'name_bn' => 'ভোলা', 'name_en' => 'Bhola', 'upazilas' => [
                        ['slug' => 'bhola-sadar', 'name_bn' => 'ভোলা সদর', 'name_en' => 'Bhola Sadar'],
                        ['slug' => 'borhanuddin', 'name_bn' => 'বোরহানউদ্দিন', 'name_en' => 'Borhanuddin'],
                        ['slug' => 'charfasson', 'name_bn' => 'চরফ্যাশন', 'name_en' => 'Charfasson'],
                        ['slug' => 'daulatkhan', 'name_bn' => 'দৌলতখান', 'name_en' => 'Daulatkhan'],
                        ['slug' => 'lalmohan', 'name_bn' => 'লালমোহন', 'name_en' => 'Lalmohan'],
                        ['slug' => 'manpura', 'name_bn' => 'মনপুরা', 'name_en' => 'Manpura'],
                        ['slug' => 'tazumuddin', 'name_bn' => 'তজুমদ্দিন', 'name_en' => 'Tazumuddin'],
                    ]],
                    ['slug' => 'patuakhali', 'name_bn' => 'পটুয়াখালী', 'name_en' => 'Patuakhali', 'upazilas' => [
                        ['slug' => 'patuakhali-sadar', 'name_bn' => 'পটুয়াখালী সদর', 'name_en' => 'Patuakhali Sadar'],
                        ['slug' => 'bauphal', 'name_bn' => 'বাউফল', 'name_en' => 'Bauphal'],
                        ['slug' => 'dashmina', 'name_bn' => 'দশমিনা', 'name_en' => 'Dashmina'],
                        ['slug' => 'dumki', 'name_bn' => 'দুমকি', 'name_en' => 'Dumki'],
                        ['slug' => 'galachipa', 'name_bn' => 'গলাচিপা', 'name_en' => 'Galachipa'],
                        ['slug' => 'kalapara', 'name_bn' => 'কলাপাড়া', 'name_en' => 'Kalapara'],
                        ['slug' => 'mirza-gopalpur', 'name_bn' => 'মির্জাগঞ্জ', 'name_en' => 'Mirzaganj'],
                        ['slug' => 'rangabali', 'name_bn' => 'রাঙ্গাবালী', 'name_en' => 'Rangabali'],
                    ]],
                    ['slug' => 'pirojpur', 'name_bn' => 'পিরোজপুর', 'name_en' => 'Pirojpur', 'upazilas' => [
                        ['slug' => 'pirojpur-sadar', 'name_bn' => 'পিরোজপুর সদর', 'name_en' => 'Pirojpur Sadar'],
                        ['slug' => 'bhandaria', 'name_bn' => 'ভান্ডারিয়া', 'name_en' => 'Bhandaria'],
                        ['slug' => 'kawkhali', 'name_bn' => 'কাউখালী', 'name_en' => 'Kawkhali'],
                        ['slug' => 'mathbaria', 'name_bn' => 'মঠবাড়িয়া', 'name_en' => 'Mathbaria'],
                        ['slug' => 'nazirpur', 'name_bn' => 'নাজিরপুর', 'name_en' => 'Nazirpur'],
                        ['slug' => 'nesarabad', 'name_bn' => 'নেছারাবাদ', 'name_en' => 'Nesarabad'],
                        ['slug' => 'zianagar', 'name_bn' => 'জিয়ানগর', 'name_en' => 'Zianagar'],
                    ]],
                    ['slug' => 'barguna', 'name_bn' => 'বরগুনা', 'name_en' => 'Barguna', 'upazilas' => [
                        ['slug' => 'barguna-sadar', 'name_bn' => 'বরগুনা সদর', 'name_en' => 'Barguna Sadar'],
                        ['slug' => 'amtali', 'name_bn' => 'আমতলী', 'name_en' => 'Amtali'],
                        ['slug' => 'bamna', 'name_bn' => 'বামনা', 'name_en' => 'Bamna'],
                        ['slug' => 'betagi', 'name_bn' => 'বেতাগী', 'name_en' => 'Betagi'],
                        ['slug' => 'patharghata', 'name_bn' => 'পাথরঘাটা', 'name_en' => 'Patharghata'],
                        ['slug' => 'taltali', 'name_bn' => 'তালতলী', 'name_en' => 'Taltali'],
                    ]],
                    ['slug' => 'jhalokati', 'name_bn' => 'ঝালকাঠি', 'name_en' => 'Jhalokati', 'upazilas' => [
                        ['slug' => 'jhalokati-sadar', 'name_bn' => 'ঝালকাঠি সদর', 'name_en' => 'Jhalokati Sadar'],
                        ['slug' => 'kathalia', 'name_bn' => 'কাঁঠালিয়া', 'name_en' => 'Kathalia'],
                        ['slug' => 'nalchity', 'name_bn' => 'নলছিটি', 'name_en' => 'Nalchity'],
                        ['slug' => 'rajapur', 'name_bn' => 'রাজাপুর', 'name_en' => 'Rajapur'],
                    ]],
                ],
            ],
            [
                'slug' => 'sylhet', 'name_bn' => 'সিলেট', 'name_en' => 'Sylhet',
                'districts' => [
                    ['slug' => 'sylhet', 'name_bn' => 'সিলেট', 'name_en' => 'Sylhet', 'upazilas' => [
                        ['slug' => 'sylhet-sadar', 'name_bn' => 'সিলেট সদর', 'name_en' => 'Sylhet Sadar'],
                        ['slug' => 'balaganj', 'name_bn' => 'বালাগঞ্জ', 'name_en' => 'Balaganj'],
                        ['slug' => 'beanibazar', 'name_bn' => 'বিয়ানীবাজার', 'name_en' => 'Beanibazar'],
                        ['slug' => 'bishwanath', 'name_bn' => 'বিশ্বনাথ', 'name_en' => 'Bishwanath'],
                        ['slug' => 'companiganj-sylhet', 'name_bn' => 'কোম্পানিগঞ্জ', 'name_en' => 'Companiganj'],
                        ['slug' => 'fenchuganj', 'name_bn' => 'ফেঞ্চুগঞ্জ', 'name_en' => 'Fenchuganj'],
                        ['slug' => 'golapganj', 'name_bn' => 'গোলাপগঞ্জ', 'name_en' => 'Golapganj'],
                        ['slug' => 'gowainghat', 'name_bn' => 'গোয়াইনঘাট', 'name_en' => 'Gowainghat'],
                        ['slug' => 'jaintiapur', 'name_bn' => 'জৈন্তাপুর', 'name_en' => 'Jaintiapur'],
                        ['slug' => 'kanaighat', 'name_bn' => 'কানাইঘাট', 'name_en' => 'Kanaighat'],
                        ['slug' => 'osmani-nagar', 'name_bn' => 'ওসমানীনগর', 'name_en' => 'Osmani Nagar'],
                        ['slug' => 'south-surma', 'name_bn' => 'দক্ষিণ সুরমা', 'name_en' => 'South Surma'],
                        ['slug' => 'zakiganj', 'name_bn' => 'জকিগঞ্জ', 'name_en' => 'Zakiganj'],
                    ]],
                    ['slug' => 'sunamganj', 'name_bn' => 'সুনামগঞ্জ', 'name_en' => 'Sunamganj', 'upazilas' => [
                        ['slug' => 'sunamganj-sadar', 'name_bn' => 'সুনামগঞ্জ সদর', 'name_en' => 'Sunamganj Sadar'],
                        ['slug' => 'bishwamvarpur', 'name_bn' => 'বিশ্বম্ভরপুর', 'name_en' => 'Bishwamvarpur'],
                        ['slug' => 'chhatak', 'name_bn' => 'ছাতক', 'name_en' => 'Chhatak'],
                        ['slug' => 'derai', 'name_bn' => 'দিরাই', 'name_en' => 'Derai'],
                        ['slug' => 'dharampasha', 'name_bn' => 'ধর্মপাশা', 'name_en' => 'Dharampasha'],
                        ['slug' => 'dowarabazar', 'name_bn' => 'দোয়ারাবাজার', 'name_en' => 'Dowarabazar'],
                        ['slug' => 'jagannathpur', 'name_bn' => 'জগন্নাথপুর', 'name_en' => 'Jagannathpur'],
                        ['slug' => 'jamalganj', 'name_bn' => 'জামালগঞ্জ', 'name_en' => 'Jamalganj'],
                        ['slug' => 'sullah', 'name_bn' => 'সুল্লা', 'name_en' => 'Sullah'],
                        ['slug' => 'tahirpur', 'name_bn' => 'তাহিরপুর', 'name_en' => 'Tahirpur'],
                    ]],
                    ['slug' => 'habiganj', 'name_bn' => 'হবিগঞ্জ', 'name_en' => 'Habiganj', 'upazilas' => [
                        ['slug' => 'habiganj-sadar', 'name_bn' => 'হবিগঞ্জ সদর', 'name_en' => 'Habiganj Sadar'],
                        ['slug' => 'ajmiriganj', 'name_bn' => 'আজমিরিগঞ্জ', 'name_en' => 'Ajmiriganj'],
                        ['slug' => 'bahubal', 'name_bn' => 'বাহুবল', 'name_en' => 'Bahubal'],
                        ['slug' => 'banncharampur-habiganj', 'name_bn' => 'বানিয়াচং', 'name_en' => 'Baniachong'],
                        ['slug' => 'chunarughat', 'name_bn' => 'চুনারুঘাট', 'name_en' => 'Chunarughat'],
                        ['slug' => 'lakhai', 'name_bn' => 'লাখাই', 'name_en' => 'Lakhai'],
                        ['slug' => 'madhabpur', 'name_bn' => 'মাধবপুর', 'name_en' => 'Madhabpur'],
                        ['slug' => 'nabiganj', 'name_bn' => 'নবীগঞ্জ', 'name_en' => 'Nabiganj'],
                    ]],
                    ['slug' => 'moulvibazar', 'name_bn' => 'মৌলভীবাজার', 'name_en' => 'Moulvibazar', 'upazilas' => [
                        ['slug' => 'moulvibazar-sadar', 'name_bn' => 'মৌলভীবাজার সদর', 'name_en' => 'Moulvibazar Sadar'],
                        ['slug' => 'barlekha', 'name_bn' => 'বড়লেখা', 'name_en' => 'Barlekha'],
                        ['slug' => 'juri', 'name_bn' => 'জুড়ী', 'name_en' => 'Juri'],
                        ['slug' => 'kamalganj', 'name_bn' => 'কমলগঞ্জ', 'name_en' => 'Kamalganj'],
                        ['slug' => 'kulaura', 'name_bn' => 'কুলাউড়া', 'name_en' => 'Kulaura'],
                        ['slug' => 'rajnagar', 'name_bn' => 'রাজনগর', 'name_en' => 'Rajnagar'],
                        ['slug' => 'sreemangal', 'name_bn' => 'শ্রীমঙ্গল', 'name_en' => 'Sreemangal'],
                    ]],
                ],
            ],
            [
                'slug' => 'rangpur', 'name_bn' => 'রংপুর', 'name_en' => 'Rangpur',
                'districts' => [
                    ['slug' => 'rangpur', 'name_bn' => 'রংপুর', 'name_en' => 'Rangpur', 'upazilas' => [
                        ['slug' => 'rangpur-sadar', 'name_bn' => 'রংপুর সদর', 'name_en' => 'Rangpur Sadar'],
                        ['slug' => 'badarganj', 'name_bn' => 'বদরগঞ্জ', 'name_en' => 'Badarganj'],
                        ['slug' => 'gangachara', 'name_bn' => 'গংগাচড়া', 'name_en' => 'Gangachara'],
                        ['slug' => 'kaunia', 'name_bn' => 'কাউনিয়া', 'name_en' => 'Kaunia'],
                        ['slug' => 'mithapukur', 'name_bn' => 'মিঠাপুকুর', 'name_en' => 'Mithapukur'],
                        ['slug' => 'pirgachha', 'name_bn' => 'পীরগাছা', 'name_en' => 'Pirgachha'],
                        ['slug' => 'pirganj-rangpur', 'name_bn' => 'পীরগঞ্জ', 'name_en' => 'Pirganj'],
                        ['slug' => 'taraganj', 'name_bn' => 'তারাগঞ্জ', 'name_en' => 'Taraganj'],
                    ]],
                    ['slug' => 'dinajpur', 'name_bn' => 'দিনাজপুর', 'name_en' => 'Dinajpur', 'upazilas' => [
                        ['slug' => 'dinajpur-sadar', 'name_bn' => 'দিনাজপুর সদর', 'name_en' => 'Dinajpur Sadar'],
                        ['slug' => 'birampur', 'name_bn' => 'বিরামপুর', 'name_en' => 'Birampur'],
                        ['slug' => 'birganj', 'name_bn' => 'বীরগঞ্জ', 'name_en' => 'Birganj'],
                        ['slug' => 'biral', 'name_bn' => 'বিরল', 'name_en' => 'Biral'],
                        ['slug' => 'bochaganj', 'name_bn' => 'বোচাগঞ্জ', 'name_en' => 'Bochaganj'],
                        ['slug' => 'chirirbandar', 'name_bn' => 'চিরিরবন্দর', 'name_en' => 'Chirirbandar'],
                        ['slug' => 'fulbari', 'name_bn' => 'ফুলবাড়ী', 'name_en' => 'Fulbari'],
                        ['slug' => 'ghoraghat', 'name_bn' => 'ঘোড়াঘাট', 'name_en' => 'Ghoraghat'],
                        ['slug' => 'hakimpur', 'name_bn' => 'হাকিমপুর', 'name_en' => 'Hakimpur'],
                        ['slug' => 'kaharole', 'name_bn' => 'কাহারোল', 'name_en' => 'Kaharole'],
                        ['slug' => 'khansama', 'name_bn' => 'খানসামা', 'name_en' => 'Khansama'],
                        ['slug' => 'nawabganj', 'name_bn' => 'নবাবগঞ্জ', 'name_en' => 'Nawabganj'],
                        ['slug' => 'parbatipur', 'name_bn' => 'পার্বতীপুর', 'name_en' => 'Parbatipur'],
                    ]],
                    ['slug' => 'gaibandha', 'name_bn' => 'গাইবান্ধা', 'name_en' => 'Gaibandha', 'upazilas' => [
                        ['slug' => 'gaibandha-sadar', 'name_bn' => 'গাইবান্ধা সদর', 'name_en' => 'Gaibandha Sadar'],
                        ['slug' => 'fulchhari', 'name_bn' => 'ফুলছড়ি', 'name_en' => 'Fulchhari'],
                        ['slug' => 'gobindaganj', 'name_bn' => 'গোবিন্দগঞ্জ', 'name_en' => 'Gobindaganj'],
                        ['slug' => 'palashbari', 'name_bn' => 'পলাশবাড়ী', 'name_en' => 'Palashbari'],
                        ['slug' => 'sadullapur', 'name_bn' => 'সাদুল্লাপুর', 'name_en' => 'Sadullapur'],
                        ['slug' => 'sghata', 'name_bn' => 'সাঘাটা', 'name_en' => 'Saghata'],
                        ['slug' => 'sundarganj', 'name_bn' => 'সুন্দরগঞ্জ', 'name_en' => 'Sundarganj'],
                    ]],
                    ['slug' => 'kurigram', 'name_bn' => 'কুড়িগ্রাম', 'name_en' => 'Kurigram', 'upazilas' => [
                        ['slug' => 'kurigram-sadar', 'name_bn' => 'কুড়িগ্রাম সদর', 'name_en' => 'Kurigram Sadar'],
                        ['slug' => 'bhurungamari', 'name_bn' => 'ভুরুঙ্গামারী', 'name_en' => 'Bhurungamari'],
                        ['slug' => 'char-rajibpur', 'name_bn' => 'চর রাজিবপুর', 'name_en' => 'Char Rajibpur'],
                        ['slug' => 'chilmari', 'name_bn' => 'চিলমারী', 'name_en' => 'Chilmari'],
                        ['slug' => 'nageshwari', 'name_bn' => 'নাগেশ্বরী', 'name_en' => 'Nageshwari'],
                        ['slug' => 'phulbari-kurigram', 'name_bn' => 'ফুলবাড়ী', 'name_en' => 'Phulbari'],
                        ['slug' => 'rajibpur', 'name_bn' => 'রাজীবপুর', 'name_en' => 'Rajibpur'],
                        ['slug' => 'rajarhat', 'name_bn' => 'রাজারহাট', 'name_en' => 'Rajarhat'],
                        ['slug' => 'raumari', 'name_bn' => 'রৌমারী', 'name_en' => 'Raumari'],
                        ['slug' => 'ulipur', 'name_bn' => 'উলিপুর', 'name_en' => 'Ulipur'],
                    ]],
                    ['slug' => 'lalmonirhat', 'name_bn' => 'লালমনিরহাট', 'name_en' => 'Lalmonirhat', 'upazilas' => [
                        ['slug' => 'lalmonirhat-sadar', 'name_bn' => 'লালমনিরহাট সদর', 'name_en' => 'Lalmonirhat Sadar'],
                        ['slug' => 'aditmari', 'name_bn' => 'আদিতমারী', 'name_en' => 'Aditmari'],
                        ['slug' => 'hatibandha', 'name_bn' => 'হাতীবান্ধা', 'name_en' => 'Hatibandha'],
                        ['slug' => 'kaliganj-lalmonirhat', 'name_bn' => 'কালীগঞ্জ', 'name_en' => 'Kaliganj'],
                        ['slug' => 'patgram', 'name_bn' => 'পাটগ্রাম', 'name_en' => 'Patgram'],
                    ]],
                    ['slug' => 'nilphamari', 'name_bn' => 'নীলফামারী', 'name_en' => 'Nilphamari', 'upazilas' => [
                        ['slug' => 'nilphamari-sadar', 'name_bn' => 'নীলফামারী সদর', 'name_en' => 'Nilphamari Sadar'],
                        ['slug' => 'dimla', 'name_bn' => 'ডিমলা', 'name_en' => 'Dimla'],
                        ['slug' => 'domar', 'name_bn' => 'ডোমার', 'name_en' => 'Domar'],
                        ['slug' => 'jaldhaka', 'name_bn' => 'জলঢাকা', 'name_en' => 'Jaldhaka'],
                        ['slug' => 'kishoreganj-nilphamari', 'name_bn' => 'কিশোরগঞ্জ', 'name_en' => 'Kishoreganj'],
                        ['slug' => 'saidpur', 'name_bn' => 'সৈয়দপুর', 'name_en' => 'Saidpur'],
                    ]],
                    ['slug' => 'panchagarh', 'name_bn' => 'পঞ্চগড়', 'name_en' => 'Panchagarh', 'upazilas' => [
                        ['slug' => 'panchagarh-sadar', 'name_bn' => 'পঞ্চগড় সদর', 'name_en' => 'Panchagarh Sadar'],
                        ['slug' => 'atwari', 'name_bn' => 'আটোয়ারী', 'name_en' => 'Atwari'],
                        ['slug' => 'boda', 'name_bn' => 'বোদা', 'name_en' => 'Boda'],
                        ['slug' => 'debiganj', 'name_bn' => 'দেবীগঞ্জ', 'name_en' => 'Debiganj'],
                        ['slug' => 'tetulia', 'name_bn' => 'তেঁতুলিয়া', 'name_en' => 'Tetulia'],
                    ]],
                    ['slug' => 'thakurgaon', 'name_bn' => 'ঠাকুরগাঁও', 'name_en' => 'Thakurgaon', 'upazilas' => [
                        ['slug' => 'thakurgaon-sadar', 'name_bn' => 'ঠাকুরগাঁও সদর', 'name_en' => 'Thakurgaon Sadar'],
                        ['slug' => 'baliadangi', 'name_bn' => 'বালিয়াডাঙ্গী', 'name_en' => 'Baliadangi'],
                        ['slug' => 'haripur', 'name_bn' => 'হরিপুর', 'name_en' => 'Haripur'],
                        ['slug' => 'pirganj-thakurgaon', 'name_bn' => 'পীরগঞ্জ', 'name_en' => 'Pirganj'],
                        ['slug' => 'ranisankail', 'name_bn' => 'রাণীশংকৈল', 'name_en' => 'Ranisankail'],
                    ]],
                ],
            ],
            [
                'slug' => 'mymensingh', 'name_bn' => 'ময়মনসিংহ', 'name_en' => 'Mymensingh',
                'districts' => [
                    ['slug' => 'mymensingh', 'name_bn' => 'ময়মনসিংহ', 'name_en' => 'Mymensingh', 'upazilas' => [
                        ['slug' => 'mymensingh-sadar', 'name_bn' => 'ময়মনসিংহ সদর', 'name_en' => 'Mymensingh Sadar'],
                        ['slug' => 'bhaluka', 'name_bn' => 'ভালুকা', 'name_en' => 'Bhaluka'],
                        ['slug' => 'dhobaura', 'name_bn' => 'ধোবাউড়া', 'name_en' => 'Dhobaura'],
                        ['slug' => 'fulbaria', 'name_bn' => 'ফুলবাড়িয়া', 'name_en' => 'Fulbaria'],
                        ['slug' => 'gaffargaon', 'name_bn' => 'গফরগাঁও', 'name_en' => 'Gaffargaon'],
                        ['slug' => 'gauripur', 'name_bn' => 'গৌরীপুর', 'name_en' => 'Gauripur'],
                        ['slug' => 'haluaghat', 'name_bn' => 'হালুয়াঘাট', 'name_en' => 'Haluaghat'],
                        ['slug' => 'ishwarganj', 'name_bn' => 'ঈশ্বরগঞ্জ', 'name_en' => 'Ishwarganj'],
                        ['slug' => 'muktagachha', 'name_bn' => 'মুক্তাগাছা', 'name_en' => 'Muktagachha'],
                        ['slug' => 'nandail', 'name_bn' => 'নান্দাইল', 'name_en' => 'Nandail'],
                        ['slug' => 'phulpur', 'name_bn' => 'ফুলপুর', 'name_en' => 'Phulpur'],
                        ['slug' => 'trishal', 'name_bn' => 'ত্রিশাল', 'name_en' => 'Trishal'],
                    ]],
                    ['slug' => 'jamalpur', 'name_bn' => 'জামালপুর', 'name_en' => 'Jamalpur', 'upazilas' => [
                        ['slug' => 'jamalpur-sadar', 'name_bn' => 'জামালপুর সদর', 'name_en' => 'Jamalpur Sadar'],
                        ['slug' => 'bakshiganj', 'name_bn' => 'বকশীগঞ্জ', 'name_en' => 'Bakshiganj'],
                        ['slug' => 'dewanganj', 'name_bn' => 'দেওয়ানগঞ্জ', 'name_en' => 'Dewanganj'],
                        ['slug' => 'islampur', 'name_bn' => 'ইসলামপুর', 'name_en' => 'Islampur'],
                        ['slug' => 'madarganj', 'name_bn' => 'মাদারগঞ্জ', 'name_en' => 'Madarganj'],
                        ['slug' => 'melandaha', 'name_bn' => 'মেলান্দহ', 'name_en' => 'Melandaha'],
                        ['slug' => 'sarishabari', 'name_bn' => 'সরিষাবাড়ী', 'name_en' => 'Sarishabari'],
                    ]],
                    ['slug' => 'netrokona', 'name_bn' => 'নেত্রকোণা', 'name_en' => 'Netrokona', 'upazilas' => [
                        ['slug' => 'netrokona-sadar', 'name_bn' => 'নেত্রকোণা সদর', 'name_en' => 'Netrokona Sadar'],
                        ['slug' => 'atpara', 'name_bn' => 'আটপাড়া', 'name_en' => 'Atpara'],
                        ['slug' => 'barhatta', 'name_bn' => 'বারহাট্টা', 'name_en' => 'Barhatta'],
                        ['slug' => 'durgapur-netrokona', 'name_bn' => 'দুর্গাপুর', 'name_en' => 'Durgapur'],
                        ['slug' => 'kalmakanda', 'name_bn' => 'কলমাকান্দা', 'name_en' => 'Kalmakanda'],
                        ['slug' => 'kendua', 'name_bn' => 'কেন্দুয়া', 'name_en' => 'Kendua'],
                        ['slug' => 'khaliajuri', 'name_bn' => 'খালিয়াজুড়ি', 'name_en' => 'Khaliajuri'],
                        ['slug' => 'madan', 'name_bn' => 'মদন', 'name_en' => 'Madan'],
                        ['slug' => 'mohanganj', 'name_bn' => 'মোহনগঞ্জ', 'name_en' => 'Mohanganj'],
                        ['slug' => 'purbadhala', 'name_bn' => 'পূর্বধলা', 'name_en' => 'Purbadhala'],
                    ]],
                    ['slug' => 'sherpur', 'name_bn' => 'শেরপুর', 'name_en' => 'Sherpur', 'upazilas' => [
                        ['slug' => 'sherpur-sadar', 'name_bn' => 'শেরপুর সদর', 'name_en' => 'Sherpur Sadar'],
                        ['slug' => 'jhenaigati', 'name_bn' => 'ঝিনাইগাতী', 'name_en' => 'Jhenaigati'],
                        ['slug' => 'nakla', 'name_bn' => 'নকলা', 'name_en' => 'Nakla'],
                        ['slug' => 'nalitabari', 'name_bn' => 'নালিতাবাড়ী', 'name_en' => 'Nalitabari'],
                        ['slug' => 'sreebardi', 'name_bn' => 'শ্রীবরদী', 'name_en' => 'Sreebardi'],
                    ]],
                ],
            ],
        ];

        foreach ($divisions as $divData) {
            $division = Division::firstOrCreate(
                ['slug' => $divData['slug']],
                ['name_bn' => $divData['name_bn'], 'name_en' => $divData['name_en']]
            );

            foreach ($divData['districts'] as $distData) {
                $district = District::firstOrCreate(
                    ['slug' => $distData['slug'], 'division_id' => $division->id],
                    ['name_bn' => $distData['name_bn'], 'name_en' => $distData['name_en']]
                );

                foreach ($distData['upazilas'] as $upaData) {
                    Upazila::firstOrCreate(
                        ['slug' => $upaData['slug'], 'district_id' => $district->id],
                        ['name_bn' => $upaData['name_bn'], 'name_en' => $upaData['name_en']]
                    );
                }
            }
        }
    }
}
