<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General
            [
                'key' => 'site_name',
                'value' => 'নব দিগন্ত',
                'group' => 'general',
                'type' => 'text',
                'label_bn' => 'সাইটের নাম (বাংলা)',
                'label_en' => 'Site Name (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'site_name_en',
                'value' => 'Nobo Digonto',
                'group' => 'general',
                'type' => 'text',
                'label_bn' => 'সাইটের নাম (ইংরেজি)',
                'label_en' => 'Site Name (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'site_tagline',
                'value' => 'সঠিক সংবাদ সবার আগে',
                'group' => 'general',
                'type' => 'text',
                'label_bn' => 'সাইট ট্যাগলাইন',
                'label_en' => 'Site Tagline',
                'is_public' => true,
            ],
            [
                'key' => 'site_logo',
                'value' => null,
                'group' => 'general',
                'type' => 'image',
                'label_bn' => 'সাইট লোগো (বাংলা)',
                'label_en' => 'Site Logo (Bangla)',
                'description_bn' => 'বাংলা সংস্করণের হেডারে প্রদর্শিত হবে (PNG বা SVG, প্রস্তাবিত আকার: ২৪০×৬০ পিক্সেল)',
                'description_en' => 'Shown in the Bangla edition header (PNG or SVG, recommended: 240×60 px)',
                'is_public' => true,
            ],
            [
                'key' => 'site_logo_en',
                'value' => null,
                'group' => 'general',
                'type' => 'image',
                'label_bn' => 'সাইট লোগো (ইংরেজি)',
                'label_en' => 'Site Logo (English)',
                'description_bn' => 'ইংরেজি সংস্করণের হেডারে প্রদর্শিত হবে। খালি রাখলে বাংলা লোগোই ব্যবহার হবে।',
                'description_en' => 'Shown in the English edition header. Falls back to the Bangla logo if left empty.',
                'is_public' => true,
            ],
            [
                'key' => 'og_default_image',
                'value' => null,
                'group' => 'seo',
                'type' => 'image',
                'label_bn' => 'ডিফল্ট OG ছবি (১২০০×৬৩০ পিক্সেল)',
                'label_en' => 'Default OG Image (1200×630 px)',
                'description_bn' => 'ফেসবুক, টুইটার শেয়ারে দেখানো ডিফল্ট ছবি। নির্দিষ্ট ছবি না থাকলে এটি ব্যবহার হবে।',
                'description_en' => 'Default image shown when sharing on Facebook, Twitter etc. Used when no featured image is available.',
                'is_public' => true,
            ],
            [
                'key' => 'site_favicon',
                'value' => null,
                'group' => 'general',
                'type' => 'image',
                'label_bn' => 'ফেভিকন',
                'label_en' => 'Favicon',
                'description_bn' => 'ব্রাউজার ট্যাবে প্রদর্শিত আইকন (ICO বা PNG, ৩২×৩২ পিক্সেল)',
                'description_en' => 'Browser tab icon (ICO or PNG, 32×32 px)',
                'is_public' => true,
            ],
            [
                'key' => 'contact_email',
                'value' => 'info@nobodigonto.com',
                'group' => 'general',
                'type' => 'text',
                'label_bn' => 'যোগাযোগ ইমেইল',
                'label_en' => 'Contact Email',
                'is_public' => true,
            ],
            [
                'key' => 'contact_phone',
                'value' => '+880 1234 567890',
                'group' => 'general',
                'type' => 'text',
                'label_bn' => 'যোগাযোগ ফোন',
                'label_en' => 'Contact Phone',
                'is_public' => true,
            ],
            [
                'key' => 'notice_enabled',
                'value' => 'false',
                'group' => 'general',
                'type' => 'boolean',
                'label_bn' => 'নোটিশ সক্রিয়',
                'label_en' => 'Notice Enabled',
                'is_public' => true,
            ],
            [
                'key' => 'notice_text_bn',
                'value' => 'নোটিশ: ওয়েবসাইট পরিবর্তনের কাজ চলমান থাকায় কিছু নিউজ দেখা যাচ্ছে না। সাময়িক এ বিভ্রাটের জন্য আমরা দুঃখিত। — সম্পাদক',
                'group' => 'general',
                'type' => 'textarea',
                'label_bn' => 'নোটিশ টেক্সট (বাংলা)',
                'label_en' => 'Notice Text (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'notice_text_en',
                'value' => 'Notice: Some articles may not be visible as website maintenance is underway. We apologise for any inconvenience. — Editor',
                'group' => 'general',
                'type' => 'textarea',
                'label_bn' => 'নোটিশ টেক্সট (ইংরেজি)',
                'label_en' => 'Notice Text (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'free_article_limit',
                'value' => '10',
                'group' => 'general',
                'type' => 'integer',
                'label_bn' => 'ফ্রি আর্টিকেল লিমিট',
                'label_en' => 'Free Article Limit',
                'is_public' => false,
            ],

            // SEO
            [
                'key' => 'meta_title',
                'value' => 'নব দিগন্ত - নির্ভরযোগ্য সংবাদ মাধ্যম',
                'group' => 'seo',
                'type' => 'text',
                'label_bn' => 'মেটা টাইটেল',
                'label_en' => 'Meta Title',
                'is_public' => true,
            ],
            [
                'key' => 'meta_description',
                'value' => 'নব দিগন্ত বাংলাদেশের অন্যতম শীর্ষস্থানীয় অনলাইন সংবাদ মাধ্যম।',
                'group' => 'seo',
                'type' => 'textarea',
                'label_bn' => 'মেটা বর্ণনা (বাংলা)',
                'label_en' => 'Meta Description (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'meta_description_en',
                'value' => 'Nobo Digonto is one of Bangladesh\'s leading online news portals. Stay informed with the latest breaking news, analysis and opinion.',
                'group' => 'seo',
                'type' => 'textarea',
                'label_bn' => 'মেটা বর্ণনা (ইংরেজি)',
                'label_en' => 'Meta Description (EN)',
                'is_public' => true,
            ],

            // Social
            [
                'key' => 'facebook_url',
                'value' => 'https://facebook.com/nobodigonto',
                'group' => 'social',
                'type' => 'text',
                'label_bn' => 'ফেসবুক লিঙ্ক',
                'label_en' => 'Facebook URL',
                'is_public' => true,
            ],
            [
                'key' => 'twitter_url',
                'value' => 'https://twitter.com/nobodigonto',
                'group' => 'social',
                'type' => 'text',
                'label_bn' => 'টুইটার লিঙ্ক',
                'label_en' => 'Twitter URL',
                'is_public' => true,
            ],
            [
                'key' => 'youtube_url',
                'value' => 'https://youtube.com/nobodigonto',
                'group' => 'social',
                'type' => 'text',
                'label_bn' => 'ইউটিউব লিঙ্ক',
                'label_en' => 'YouTube URL',
                'is_public' => true,
            ],
            [
                'key' => 'linkedin_url',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label_bn' => 'লিংকডইন লিঙ্ক',
                'label_en' => 'LinkedIn URL',
                'is_public' => true,
            ],
            [
                'key' => 'tiktok_url',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label_bn' => 'টিকটক লিঙ্ক',
                'label_en' => 'TikTok URL',
                'is_public' => true,
            ],
            [
                'key' => 'instagram_url',
                'value' => '',
                'group' => 'social',
                'type' => 'text',
                'label_bn' => 'ইনস্টাগ্রাম লিঙ্ক',
                'label_en' => 'Instagram URL',
                'is_public' => true,
            ],

            // System
            [
                'key' => 'maintenance_mode',
                'value' => 'false',
                'group' => 'system',
                'type' => 'boolean',
                'label_bn' => 'মেইনটেন্যান্স মোড',
                'label_en' => 'Maintenance Mode',
                'is_public' => false,
            ],
            // 'allow_registration' intentionally removed — public registration is
            // hard-disabled at the route level (routes/auth.php), so a dashboard
            // toggle for it would be a no-op and misleading.
            [
                'key' => 'comment_approval',
                'value' => 'true',
                'group' => 'system',
                'type' => 'boolean',
                'label_bn' => 'মন্তব্য অনুমোদন প্রয়োজন',
                'label_en' => 'Comment Approval Required',
                'is_public' => false,
            ],

            // Legal
            [
                'key' => 'editor_name_bn',
                'value' => 'মোহাম্মদ রহমান',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'সম্পাদকের নাম (বাংলা)',
                'label_en' => 'Editor Name (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'editor_name_en',
                'value' => 'Mohammad Rahman',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'সম্পাদকের নাম (ইংরেজি)',
                'label_en' => 'Editor Name (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'publisher_name_bn',
                'value' => 'প্রভাতী মিডিয়া লিমিটেড',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'প্রকাশকের নাম (বাংলা)',
                'label_en' => 'Publisher Name (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'publisher_name_en',
                'value' => 'nobodigonto Media Ltd.',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'প্রকাশকের নাম (ইংরেজি)',
                'label_en' => 'Publisher Name (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'office_address_bn',
                'value' => '১২৩, মতিঝিল, ঢাকা-১০০০',
                'group' => 'legal',
                'type' => 'textarea',
                'label_bn' => 'অফিসের ঠিকানা (বাংলা)',
                'label_en' => 'Office Address (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'office_address_en',
                'value' => '123, Motijheel, Dhaka-1000',
                'group' => 'legal',
                'type' => 'textarea',
                'label_bn' => 'অফিসের ঠিকানা (ইংরেজি)',
                'label_en' => 'Office Address (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'reg_number_bn',
                'value' => 'বিএনপিসি-২০২৪-০০১২৩',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'নিবন্ধন নম্বর (বাংলা)',
                'label_en' => 'Reg Number (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'reg_number_en',
                'value' => 'BNPC-2024-00123',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'নিবন্ধন নম্বর (ইংরেজি)',
                'label_en' => 'Reg Number (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'executive_editor_name_bn',
                'value' => 'মো. সাইফুল ইসলাম',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'নির্বাহী সম্পাদকের নাম (বাংলা)',
                'label_en' => 'Executive Editor Name (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'executive_editor_name_en',
                'value' => 'Md. Saiful Islam',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'নির্বাহী সম্পাদকের নাম (ইংরেজি)',
                'label_en' => 'Executive Editor Name (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'ceo_name_bn',
                'value' => 'আহমেদ হোসেন',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'প্রধান নির্বাহী কর্মকর্তার নাম (বাংলা)',
                'label_en' => 'CEO Name (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'ceo_name_en',
                'value' => 'Ahmed Hossain',
                'group' => 'legal',
                'type' => 'text',
                'label_bn' => 'প্রধান নির্বাহী কর্মকর্তার নাম (ইংরেজি)',
                'label_en' => 'CEO Name (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'office_address_uk_bn',
                'value' => '৪৫ ব্রিক লেন, লন্ডন ই১ ৬পিইউ, যুক্তরাজ্য',
                'group' => 'legal',
                'type' => 'textarea',
                'label_bn' => 'যুক্তরাজ্য অফিসের ঠিকানা (বাংলা)',
                'label_en' => 'UK Office Address (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'office_address_uk_en',
                'value' => '45 Brick Lane, London E1 6PU, United Kingdom',
                'group' => 'legal',
                'type' => 'textarea',
                'label_bn' => 'যুক্তরাজ্য অফিসের ঠিকানা (ইংরেজি)',
                'label_en' => 'UK Office Address (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'contact_phone_2',
                'value' => '+44 20 7946 0958',
                'group' => 'general',
                'type' => 'text',
                'label_bn' => 'যোগাযোগ ফোন ২',
                'label_en' => 'Contact Phone 2',
                'is_public' => true,
            ],
            [
                'key' => 'copyright_owner_bn',
                'value' => 'নব দিগন্ত',
                'group' => 'general',
                'type' => 'text',
                'label_bn' => 'কপিরাইট মালিক (বাংলা)',
                'label_en' => 'Copyright Owner (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'copyright_owner_en',
                'value' => 'Nobo Digonto',
                'group' => 'general',
                'type' => 'text',
                'label_bn' => 'কপিরাইট মালিক (ইংরেজি)',
                'label_en' => 'Copyright Owner (EN)',
                'is_public' => true,
            ],
            [
                'key' => 'copyright_notice_bn',
                'value' => 'এই ওয়েবসাইটের কোনো লেখা বা ছবি অনুমতি ছাড়া নকল করা বা অন্য কোথাও প্রকাশ করা সম্পূর্ণ বেআইনি।',
                'group' => 'general',
                'type' => 'textarea',
                'label_bn' => 'কপিরাইট নোটিশ (বাংলা)',
                'label_en' => 'Copyright Notice (BN)',
                'is_public' => true,
            ],
            [
                'key' => 'copyright_notice_en',
                'value' => 'Unauthorised reproduction of content or images from this website is strictly prohibited.',
                'group' => 'general',
                'type' => 'textarea',
                'label_bn' => 'কপিরাইট নোটিশ (ইংরেজি)',
                'label_en' => 'Copyright Notice (EN)',
                'is_public' => true,
            ],

            // Integrations / Tracking — managed from the dashboard, injected into
            // the public <head>/<body>. Kept out of the admin panel itself.
            [
                'key' => 'google_analytics_id',
                'value' => null,
                'group' => 'integrations',
                'type' => 'text',
                'label_bn' => 'Google Analytics ID (G-XXXXXXX)',
                'label_en' => 'Google Analytics ID (G-XXXXXXX)',
                'description_bn' => 'GA4 Measurement ID দিন। SPA পেজভিউ ট্র্যাকিং স্বয়ংক্রিয়ভাবে কাজ করবে। খালি রাখলে বন্ধ থাকবে।',
                'description_en' => 'GA4 Measurement ID. SPA page-view tracking is handled automatically. Leave blank to disable.',
                'is_public' => false,
            ],
            [
                'key' => 'custom_head_code',
                'value' => null,
                'group' => 'integrations',
                'type' => 'textarea',
                'label_bn' => 'কাস্টম হেড কোড (<head>)',
                'label_en' => 'Custom Head Code (<head>)',
                'description_bn' => 'ভেরিফিকেশন মেটা ট্যাগ বা অন্যান্য স্ক্রিপ্ট। পাবলিক সাইটের <head>-এ যুক্ত হবে। সতর্ক থাকুন — এখানে যা দেবেন তা হুবহু রেন্ডার হবে।',
                'description_en' => 'Verification meta tags or other scripts. Injected raw into the public site <head>. Caution: rendered exactly as entered (trusted admins only).',
                'is_public' => false,
            ],
            [
                'key' => 'custom_body_code',
                'value' => null,
                'group' => 'integrations',
                'type' => 'textarea',
                'label_bn' => 'কাস্টম বডি কোড (</body>-এর আগে)',
                'label_en' => 'Custom Body Code (before </body>)',
                'description_bn' => 'চ্যাট উইজেট বা পিক্সেলের মতো স্ক্রিপ্ট। পাবলিক সাইটের </body>-এর আগে যুক্ত হবে।',
                'description_en' => 'Scripts like chat widgets or pixels. Injected before </body> on the public site.',
                'is_public' => false,
            ],

            // Security — login 2FA master switch (per-user opt-in is on each profile).
            [
                'key' => 'email_otp_enabled',
                'value' => 'false',
                'group' => 'security',
                'type' => 'boolean',
                'label_bn' => 'ইমেইল OTP (টু-ফ্যাক্টর) — সিস্টেম-ব্যাপী',
                'label_en' => 'Email OTP (Two-Factor) — System-wide',
                'description_bn' => 'চালু থাকলে যেসব ব্যবহারকারী নিজ অ্যাকাউন্টে 2FA চালু রেখেছেন তাদের লগইনে ইমেইলে পাঠানো কোড লাগবে। বন্ধ থাকলে কারো জন্যই 2FA কাজ করবে না।',
                'description_en' => 'Master switch. When on, users who have enabled 2FA on their own account must enter an emailed code at login. When off, 2FA is disabled for everyone.',
                'is_public' => false,
            ],

            // Breaking ticker — TV-style alert (flash) ⇄ scroll cadence + limit.
            [
                'key' => 'breaking_ticker_enabled', 'value' => 'true',
                'group' => 'breaking', 'type' => 'boolean',
                'label_bn' => 'ব্রেকিং টিকার চালু', 'label_en' => 'Breaking ticker enabled',
                'description_bn' => 'সাইটের নিচে ব্রেকিং নিউজ বার দেখানো হবে কিনা।',
                'description_en' => 'Master switch for the breaking-news bar at the bottom of the site.',
                'is_public' => true,
            ],
            [
                'key' => 'breaking_alert_enabled', 'value' => 'true',
                'group' => 'breaking', 'type' => 'boolean',
                'label_bn' => 'অ্যালার্ট (ফ্ল্যাশ) ফেজ চালু', 'label_en' => 'Alert (flash) phase enabled',
                'description_bn' => 'চালু থাকলে জরুরি/ব্রেকিং শিরোনাম বড় করে ফ্ল্যাশ দেখাবে, তারপর স্ক্রল করবে। বন্ধ থাকলে শুধু স্ক্রল করবে।',
                'description_en' => 'When on, Urgent/Breaking headlines flash large, then the bar scrolls. When off, it only scrolls.',
                'is_public' => true,
            ],
            [
                'key' => 'breaking_alert_seconds', 'value' => '5',
                'group' => 'breaking', 'type' => 'number',
                'label_bn' => 'প্রতি অ্যালার্ট শিরোনামের সময় (সেকেন্ড)', 'label_en' => 'Seconds per alert headline',
                'description_bn' => 'ফ্ল্যাশ ফেজে প্রতিটি শিরোনাম কত সেকেন্ড দেখাবে।',
                'description_en' => 'How long each headline is shown during the flash phase.',
                'is_public' => true,
            ],
            [
                'key' => 'breaking_alert_cycles', 'value' => '1',
                'group' => 'breaking', 'type' => 'number',
                'label_bn' => 'অ্যালার্ট চক্রের সংখ্যা', 'label_en' => 'Alert cycles',
                'description_bn' => 'স্ক্রলে যাওয়ার আগে অ্যালার্ট শিরোনামগুলো কতবার দেখানো হবে।',
                'description_en' => 'How many times to cycle through the alert headlines before scrolling.',
                'is_public' => true,
            ],
            [
                'key' => 'breaking_scroll_seconds', 'value' => '30',
                'group' => 'breaking', 'type' => 'number',
                'label_bn' => 'স্ক্রল ফেজের সময় (সেকেন্ড)', 'label_en' => 'Scroll phase seconds',
                'description_bn' => 'অ্যালার্টে ফিরে যাওয়ার আগে কত সেকেন্ড স্ক্রল করবে।',
                'description_en' => 'How long the bar scrolls before returning to the alert phase.',
                'is_public' => true,
            ],
            [
                'key' => 'breaking_max_items', 'value' => '15',
                'group' => 'breaking', 'type' => 'number',
                'label_bn' => 'সর্বোচ্চ আইটেম', 'label_en' => 'Max items',
                'description_bn' => 'টিকারে সর্বোচ্চ কতটি ব্রেকিং আইটেম দেখানো হবে।',
                'description_en' => 'Maximum number of breaking items shown in the ticker.',
                'is_public' => true,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(['key' => $setting['key']], $setting);
        }
    }
}
